# _config.yml

# required, replace with your own information -----
title: `Unbothered:` Conversations
author: Kieth Tyler Flores
description: > 
  Hosted by Kieth Tyler Flores, Unbothered: Conversations is a podcast dedicated to exploring personal stories, life-changing moments, and the experiences that shape us. From everyday challenges to extraordinary journeys, our candid conversations offer fresh perspectives and inspiration. Recorded at Cleveland High School in Cleveland, TN, each episode uncovers the stories that deserve to be heard.
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

